services:
  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: vintage_api
    restart: unless-stopped
    environment:
      - ConnectionStrings__connection=Data Source=vintage.db
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    volumes:
      - ./DataBase:/app/SeedData
      - vintage_db_data:/app/Data
    networks:
      - vintage_network

  web:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: vintage_web
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "3000:80"
    networks:
      - vintage_network

volumes:
  vintage_db_data:
    driver: local

networks:
  vintage_network:
    driver: bridge
