// <auto-generated />
using System;
using Infrastructure.ApplicationDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(VintageDbContext))]
    [Migration("20260208183346_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("code");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Size")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("size");

                    b.Property<bool>("Sold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("sold");

                    b.Property<sbyte>("State")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("state");

                    b.Property<int?>("Stock")
                        .HasColumnType("int(11)")
                        .HasColumnName("stock");

                    b.HasKey("Code")
                        .HasName("PRIMARY");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Saleorder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "saleorder_user_userid_idx");

                    b.ToTable("saleorder", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Saleorderline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("int(11)")
                        .HasColumnName("amount");

                    b.Property<int>("ProductCode")
                        .HasColumnType("int(11)")
                        .HasColumnName("product_code");

                    b.Property<int>("SaleorderId")
                        .HasColumnType("int(11)")
                        .HasColumnName("saleorder_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProductCode" }, "saleorderline_product_productcodefk_idx");

                    b.HasIndex(new[] { "SaleorderId" }, "saleorderline_saleorder_saleorderidfk_idx");

                    b.ToTable("saleorderline", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(90)
                        .HasColumnType("varchar(90)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("email");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("State")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("state");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("username");

                    b.Property<string>("Usertype")
                        .IsRequired()
                        .HasColumnType("enum('admin','employee','client','cadet')")
                        .HasColumnName("usertype");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Saleorder", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Saleorders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("saleorder_user_useridfk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Saleorderline", b =>
                {
                    b.HasOne("Domain.Entities.Product", "ProductCodeNavigation")
                        .WithMany("Saleorderlines")
                        .HasForeignKey("ProductCode")
                        .IsRequired()
                        .HasConstraintName("saleorderline_product_productcodefk");

                    b.HasOne("Domain.Entities.Saleorder", "Saleorder")
                        .WithMany("Saleorderlines")
                        .HasForeignKey("SaleorderId")
                        .IsRequired()
                        .HasConstraintName("saleorderline_saleorder_saleorderidfk");

                    b.Navigation("ProductCodeNavigation");

                    b.Navigation("Saleorder");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("Saleorderlines");
                });

            modelBuilder.Entity("Domain.Entities.Saleorder", b =>
                {
                    b.Navigation("Saleorderlines");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Saleorders");
                });
#pragma warning restore 612, 618
        }
    }
}
